# Generated by Django 4.2.7 on 2023-12-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='producer',
            new_name='brand',
        ),
    ]
